### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by smiklosovic** [timyates/mod-jdbc-persistor#27]
@timyates 

It seems it is not maintained anymore, last commit year ago. Is there any will to update it to vert.x 2.1.5?

**Comment by timyates** [comment]
It should just work

Is this not the case?

**Comment by smiklosovic** [comment]
I tried to update it to latest vert.x and bumped lib versions. Could you have a look please?

https://github.com/timyates/mod-jdbc-persistor/pull/29

**Comment by smiklosovic** [comment]
http://pastebin.com/qYH1jLrP

**Comment by timyates** [comment]
Oddly, I cannot see where that test is expecting 5?

https://github.com/timyates/mod-jdbc-persistor/blob/master/src/test/resources/integration_tests/javascript/test_client.js#L372
On 1 Jun 2015 18:17, "Štefan Miklošovič" <notifications@github.com> wrote:

http://pastebin.com/qYH1jLrP

—
Reply to this email directly or view it on GitHub
<https://github.com/timyates/mod-jdbc-persistor/issues/27#issuecomment-107643949>
.

**Comment by smiklosovic** [comment]
me neither! :)

**Comment by timyates** [comment]
Ah, it's failing here:

https://github.com/timyates/mod-jdbc-persistor/blob/master/src/test/resources/integration_tests/javascript/test_client.js#L48

Wonder if c3p0 has changed when connection go back in the idle pool

**Comment by smiklosovic** [comment]
dunno, you are the expert. I do not see into this really.

Would you mind to look at it please? I would like to use this module in order to connect to postgresql database. If I understand that correctly, I just have to put jdbc postgresql lib to class path and set this url (1).

I tried to use other modules but it seems to me that none of them are working. This one (2) is dead, author does not have time to maintain it. This one (3) pulls whole scala runtime into my fat jar and makes it 30MB bigger and it does not even work, it throws some errors and it seems guys are not responsive.

I am looking for simple ease connection, I do not mind doing lowlevel statements as I just need to do couple of them and I prefer to use pure Java and jdbc in order to keep it simple stupid. You project consists just of couple of classes and that's all I really need.

If you would be able to align this to vert.x 2.1.5 it would be awesome. It seems there is not any new major version in 2.x stream as all efforts go to vert.x 3 hence once you update it to 2.1.5 you have pretty high chance you will never need to update it once again :)

(1) https://github.com/timyates/mod-jdbc-persistor/blob/master/src/main/java/com/bloidonia/vertx/mods/JdbcProcessor.java#L130

(2) https://github.com/monoid-us/vertx-postgresql
(3) https://github.com/vert-x/mod-mysql-postgresql

**Comment by timyates** [comment]
Good point, well made ;-)

Crazy busy ATM, but I will look into it tomorrow night assuming I can clear
my backlog (and the kids go to bed without too much fuss) ;-)

Thanks again for the PR, it makes things loads easier :-)

**Comment by smiklosovic** [comment]
:+1: waiting to hear from you back!
