### ISSUE TITLE
update project to Gradle 2

### ISSUE THREAD

**Issue by smiklosovic** [timyates/mod-jdbc-persistor#28]
please update project to use Gradle 2.2

**Comment by timyates** [comment]
Why?

Pull requests are also welcome ;-)

**Comment by timyates** [comment]
Had a go at this, it's a total nightmare, and not doable in the limited time I have available

Unfortunately, as this mod has a limited lifespan, and as it does build fine with the `./gradlew` command, I'm going to close this as `wontfix`

Of course, if anyone manages to get it to work (the `provided` configuration seems to be the biggest issue), a pull request will be gratefully received :-)
