### ISSUE TITLE
"Method prepareStatement() is not yet implemented"

### ISSUE THREAD

**Issue by rsasai** [timyates/mod-jdbc-persistor#30]
Hi

I am using HANA driver and it's been all fine with SELECT, but having problem with INSERT.

With jdbc standard way that HANA suggests, INSERT works fine:
...
    PreparedStatement pstmt = connection 
        .prepareStatement("INSERT INTO DBXXX.A001 VALUES(?,?)"); 
    pstmt.setInt(1, 293); 
    pstmt.setInt(2, 552); 
    pstmt.executeUpdate(); 

However, With your module I am calling like this (pseudocode) and it's not working:
...
    String sql = "INSERT INTO DBXXX.A001 VALUES(?,?)";
    JsonArray ja_vars = new JsonArray().addNumber(456).addNumber(654);

    eb.send(JDBC_EVENTBUS_ADDR, new JsonObject().putString("action", "insert").putString("stmt", sql)
        .putArray("values", new JsonArray().addArray( ja_vars ):

...

[vert.x-worker-thread-12] 2015-07-06T12:50:05.815+01:00 SEVERE [com.bloidonia~mod-jdbc-persistor~2.1.2-com.bloidonia.vertx.mods.JdbcProcessor-610972655]  Caught error with UPDATE.
java.sql.SQLException: An SQLException was provoked by the following failure: java.lang.UnsupportedOperationException: Method prepareStatement() is not yet implemented.
at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:74)
at com.mchange.v2.c3p0.impl.NewPooledConnection.handleThrowable(NewPooledConnection.java:505)
at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:937)
at com.bloidonia.vertx.mods.JdbcProcessor$5.initialiseStatement(JdbcProcessor.java:349)
at com.bloidonia.vertx.mods.JdbcProcessor$BatchHandler.<init>(JdbcProcessor.java:568)
at com.bloidonia.vertx.mods.JdbcProcessor$5.<init>(JdbcProcessor.java:345)
at com.bloidonia.vertx.mods.JdbcProcessor.doUpdate(JdbcProcessor.java:345)
at com.bloidonia.vertx.mods.JdbcProcessor.doUpdate(JdbcProcessor.java:334)
at com.bloidonia.vertx.mods.JdbcProcessor.handle(JdbcProcessor.java:213)
at com.bloidonia.vertx.mods.JdbcProcessor.handle(JdbcProcessor.java:47)
at org.vertx.java.core.eventbus.impl.DefaultEventBus$7.run(DefaultEventBus.java:689)
at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:170)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: Method prepareStatement() is not yet implemented.
at com.sap.db.jdbc.ConnectionSapDB.prepareStatement(ConnectionSapDB.java:2040)
at com.sap.db.jdbc.trace.Connection.prepareStatement(Connection.java:388)
at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:920)

...

In your source code, I guess that prepareStatement() is complaining "Method prepareStatement() is not yet implemented"...

...
  private void doUpdate( Message<JsonObject> message,
                         Connection connection,
                         final boolean insert,
                         TransactionalHandler transaction ) throws SQLException {
    new BatchHandler( connection, message, transaction ) {
      void initialiseStatement( Message<JsonObject> initial ) throws SQLException {
        if( insert ) {
          this.statement = connection.prepareStatement( initial.body().getString( "stmt" ), Statement.RETURN_GENERATED_KEYS ) ;
...

It would be appreciated if you could provide some insight.
To me, the fact that both standard jdbc way and your code use the same prepareStatement() and reply differenty is strange...

Thank you very much.

Uppsax

**Comment by timyates** [comment]
Looks like preparedStatements aren't supported by your driver?!

**Comment by timyates** [comment]
You might be able to change the form of your insert?

http://scn.sap.com/thread/1452293

**Comment by rsasai** [comment]
Thank you Tim for your quickest reply.

> Looks like preparedStatements aren't supported by your driver?!

The standard jdbc blocking way and jdbc-persistor both use prepareStatement().
I am using the same driver and connecting to the same DB.
Therefore, it looks to me that HANA is fine with prepareStatement, but I
don;t know why only prepareStatement in jdbc-persistor is complaining...

I have tried the version of not using (?) with jdbc-persistor, which is:

String sql_insert = "INSERT INTO DBXXX.A001 VALUES(321,126)";
eb.send(JDBC_EVENTBUS_ADDR, new JsonObject().putString("action",
"insert").putString("stmt", sql);

I get exactly the same error message:

[vert.x-worker-thread-12] 2015-07-06T12:50:05.815+01:00 SEVERE
[com.bloidonia~mod-jdbc-persistor~2.1.2-com.bloidonia.vertx.mods.JdbcProcessor-610972655]
 Caught error with UPDATE.
java.sql.SQLException: An SQLException was provoked by the following
failure: java.lang.UnsupportedOperationException: Method prepareStatement()
is not yet implemented.

, because doUpdate() in jdbc-persistor source code is calling
prepareStatement()
for all "insert"...

What do you think?

Thank you.
Uppsax




On 6 July 2015 at 13:43, Tim Yates <notifications@github.com> wrote:

> You might be able to change the form of your insert?
>
> http://scn.sap.com/thread/1452293
>
> On 6 Jul 2015 1:40 pm, "Tim Yates" <tim.yates@gmail.com> wrote:
>
> > Looks like preparedStatements aren't supported by your driver?!
> > On 6 Jul 2015 1:26 pm, "Ryu Sasai" <notifications@github.com> wrote:
> >
> >> Hi
> >>
> >> I am using HANA driver and it's been all fine with SELECT, but having
> >> problem with INSERT.
> >>
> >> With jdbc standard way that HANA suggests, INSERT works fine:
> >> ...
> >> PreparedStatement pstmt = connection
> >> .prepareStatement("INSERT INTO DBXXX.A001 VALUES(?,?)");
> >> pstmt.setInt(1, 293);
> >> pstmt.setInt(2, 552);
> >> pstmt.executeUpdate();
> >>
> >> However, With your module I am calling like this (pseudocode) and it's
> >> not working:
> >> ...
> >> String sql = "INSERT INTO DBXXX.A001 VALUES(?,?)";
> >> JsonArray ja_vars = new JsonArray().addNumber(456).addNumber(654);
> >>
> >> eb.send(JDBC_EVENTBUS_ADDR, new JsonObject().putString("action",
> "insert").putString("stmt", sql)
> >> .putArray("values", new JsonArray().addArray( ja_vars ):
> >>
> >> ...
> >>
> >> [vert.x-worker-thread-12] 2015-07-06T12:50:05.815+01:00 SEVERE
> >>
> [com.bloidonia~mod-jdbc-persistor~2.1.2-com.bloidonia.vertx.mods.JdbcProcessor-610972655]
> >> Caught error with UPDATE.
> >> java.sql.SQLException: An SQLException was provoked by the following
> >> failure: java.lang.UnsupportedOperationException: Method
> prepareStatement()
> >> is not yet implemented.
> >> at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
> >> at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
> >> at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:74)
> >> at
> >>
> com.mchange.v2.c3p0.impl.NewPooledConnection.handleThrowable(NewPooledConnection.java:505)
> >> at
> >>
> com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:937)
> >> at
> >>
> com.bloidonia.vertx.mods.JdbcProcessor$5.initialiseStatement(JdbcProcessor.java:349)
> >> at
> >>
> com.bloidonia.vertx.mods.JdbcProcessor$BatchHandler.(JdbcProcessor.java:568)
> >> at com.bloidonia.vertx.mods.JdbcProcessor$5.(JdbcProcessor.java:345)
> >> at
> com.bloidonia.vertx.mods.JdbcProcessor.doUpdate(JdbcProcessor.java:345)
> >> at
> com.bloidonia.vertx.mods.JdbcProcessor.doUpdate(JdbcProcessor.java:334)
> >> at com.bloidonia.vertx.mods.JdbcProcessor.handle(JdbcProcessor.java:213)
> >> at com.bloidonia.vertx.mods.JdbcProcessor.handle(JdbcProcessor.java:47)
> >> at
> >>
> org.vertx.java.core.eventbus.impl.DefaultEventBus$7.run(DefaultEventBus.java:689)
> >> at
> org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:170)
> >> at
> >>
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> >> at
> >>
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> >> at java.lang.Thread.run(Thread.java:745)
> >> Caused by: java.lang.UnsupportedOperationException: Method
> >> prepareStatement() is not yet implemented.
> >> at
> >>
> com.sap.db.jdbc.ConnectionSapDB.prepareStatement(ConnectionSapDB.java:2040)
> >> at
> com.sap.db.jdbc.trace.Connection.prepareStatement(Connection.java:388)
> >> at
> >>
> com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:920)
> >>
> >> ...
> >>
> >> In your source code, I guess that prepareStatement() is complaining
> >> "Method prepareStatement() is not yet implemented"...
> >>
> >> ...
> >> private void doUpdate( Message message,
> >> Connection connection,
> >> final boolean insert,
> >> TransactionalHandler transaction ) throws SQLException {
> >> new BatchHandler( connection, message, transaction ) {
> >> void initialiseStatement( Message initial ) throws SQLException {
> >> if( insert ) {
> >> this.statement = connection.prepareStatement( initial.body().getString(
> >> "stmt" ), Statement.RETURN_GENERATED_KEYS ) ;
> >> ...
> >>
> >> It would be appreciated if you could provide some insight.
> >> To me, the fact that both standard jdbc way and your code use the same
> >> prepareStatement() and reply differenty is strange...
> >>
> >> Thank you very much.
> >>
> >> Uppsax
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/timyates/mod-jdbc-persistor/issues/30>.
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timyates/mod-jdbc-persistor/issues/30#issuecomment-118842458>
> .
>



-- 

Regards



Ryu Sasai

Senior Developer



 <http://www.centiq.co.uk/systemiq/ibm-premier-partner>


Office: 0115 951 9666

Address: Charles Park, Cinderhill Road, Nottingham, NG6 8RF



www.centiq.co.uk



About Centiq – Read more
<http://www.centiq.co.uk/attachments/article/96/Introducing%20Centiq.pdf>


<http://www.centiq.co.uk/systemiq/ibm-premier-partner>

-- 
Confidentiality: This e-mail and its attachments are intended for the above 
named only and may be confidential. If they have come to you in error you 
must take no action based on them, nor must you copy or show them to 
anyone, please reply to this e-mail and highlight the error.

Security Warning: Please note that this e-mail has been created in the 
knowledge that Internet e-mail is not a 100% secure communications medium. 
We advise that you understand and observe this lack of security when 
e-mailing us.

Viruses: Although we have taken steps to ensure that this e-mail and 
attachments are free from any virus, we advise that in keeping with good 
computing practice the recipient should ensure they are actually virus free.

Centiq Ltd
Registered in England with number 3593921.
Registered office: Unit 1, Charles Park, Charles Way, Cinderhill Road, 
Nottingham, NG6 8RF

**Comment by timyates** [comment]
I'm wondering if it's the `Statement.RETURN_GENERATED_KEYS` second parameter for the [insert call](https://github.com/timyates/mod-jdbc-persistor/blob/master/src/main/java/com/bloidonia/vertx/mods/JdbcProcessor.java#L350)

Can you try calling it this way locally as see if you get the same exception?

We might have to put some sort of flag in to not do this...

**Comment by rsasai** [comment]
Tim
I was wondering the same thing!
I will get back to you shortly...
Uppsax

**Comment by timyates** [comment]
Cool, if needs be, we can put a flag into the options to skip this extra
parameter :-)  (like the PMD parameter which is to get round oracle driver
flakeyness) ;-)

**Comment by rsasai** [comment]
Hi Tim
Just to prove skipping works I made the local change and recompiled it. Insert worked!
Basically, insert is behaving exactly the same as update.  I don't know if this is the right thing to do, but it seems to be working for insert.

```Java
  private void doUpdate( Message<JsonObject> message,
                         Connection connection,
                         final boolean insert,
                         TransactionalHandler transaction ) throws SQLException {
    new BatchHandler( connection, message, transaction ) {
      void initialiseStatement( Message<JsonObject> initial ) throws SQLException {
        if( insert ) {
//HERE-------------------->>
//          this.statement = connection.prepareStatement( initial.body().getString( "stmt" ), Statement.RETURN_GENERATED_KEYS ) ;
        	this.statement = connection.prepareStatement( initial.body().getString( "stmt" ) ) ;
//HERE--------------------<<
        }
        else {
          this.statement = connection.prepareStatement( initial.body().getString( "stmt" ) ) ;
        }
      }
      public JsonObject process() throws SQLException {
        JsonObject reply = new JsonObject() ;
        ArrayList<Map<String,Object>> result = new ArrayList<Map<String,Object>>() ;
        // processing
        int nRows = 0 ;
        if( insert ) {
//HERE-------------------->>
//          while( ( resultSet != null || valueIterator.hasNext() ) &&
//                 ( batchSize == -1 || result.size() < batchSize ) ) {
//            LimitedMapListHandler handler = new LimitedMapListHandler( batchSize == -1 ? -1 : batchSize - result.size() ) ;
//            if( resultSet == null ) {
//              List<Object> params = valueIterator.next() ;
//              statementFiller.fill( statement, params ) ;
//              nRows += statement.executeUpdate() ;
//              resultSet = statement.getGeneratedKeys() ;
//            }
//            store( result, handler ) ;
//          }
//          reply.putArray( "result", JsonUtils.listOfMapsToJsonArray( result ) ) ;
            while( valueIterator.hasNext() ) {
            	List<Object> params = valueIterator.next() ;
            	statementFiller.fill( statement, params ) ;
            	nRows += statement.executeUpdate() ;
             }
//HERE--------------------<<
        }
        else {
```

What do you think?
Thanks,
Uppsax

**Comment by timyates** [comment]
Cool, so I reckon we can add a config flag to make INSERT run exactly like
an UPDATE

Then

        if( insert ) {

becomes

        if( insert && !ignoreAutogeneratedKeys ) {


Or similar?

**Comment by rsasai** [comment]
Yes, that looks right.
The only difference I can think of so far is that you lose "result" key and its value in the reply for client.
Uppsax

**Comment by rsasai** [comment]
What I mean is that what I get as reply is:
{"updated":1,"status":"ok"}
This is fine for me but I don't know for other people.
Uppsax

**Comment by timyates** [comment]
You're the only person who's had this issue, so it should be ok ;-) ;-P

**Comment by timyates** [comment]
`2.1.5` pushed to maven, so should appear in a few hours

Added a config property `ignoreAutoGeneratedKeys` which you'll need to set to `true` for testing :-)

Documented in the readme (hopefully in an understandable way)

**Comment by rsasai** [comment]
Thank you very much Tim, this is brilliant.
Uppsax

**Comment by timyates** [comment]
Cool, glad it works :-D
